version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: stockscanner-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: stockscanner
      POSTGRES_USER: stockuser
      POSTGRES_PASSWORD: stockpassword

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: stockscanner-redis

    restart: unless-stopped

    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend

    container_name: stockscanner-api

    restart: unless-stopped

    env_file:
      - ./backend/.env

    depends_on:
      - postgres
      - redis

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

volumes:
  postgres_data:
